import type { DataType } from "./types"

// Initial data for the application
export const initialData: DataType = {
  activities: [
    {
      date: "2025-05-19",
      timeOfDay: "Evening",
      activity: "Study",
      activityType: "Study",
      details: "Preparing for midterm exams",
      weather: "Rainy",
      statChanges: {
        Knowledge: 1,
      },
    },
    {
      date: "2025-05-20",
      timeOfDay: "Evening",
      activity: "Work Part-time",
      activityType: "Work",
      details: "Shift at Junes Department Store",
      weather: "Cloudy",
      statChanges: {
        Diligence: 1,
        Understanding: 1,
      },
    },
    {
      date: "2025-05-21",
      timeOfDay: "Evening",
      activity: "Read Book",
      activityType: "Reading",
      details: "The Lovely Man by Tatsumi",
      weather: "Sunny",
      statChanges: {
        Knowledge: 1,
      },
    },
    {
      date: "2025-05-22",
      timeOfDay: "Evening",
      activity: "Social Link",
      activityType: "Social",
      details: "Hanging out with Yosuke at the food court",
      weather: "Sunny",
      statChanges: {
        Expression: 1,
      },
    },
    {
      date: "2025-05-23",
      timeOfDay: "Evening",
      activity: "Training",
      activityType: "Training",
      details: "Practicing at the riverbed",
      weather: "Cloudy",
      statChanges: {
        Courage: 1,
      },
    },
    {
      date: "2025-05-24",
      timeOfDay: "Morning",
      activity: "Shopping",
      activityType: "Social",
      details: "Buying equipment at Daidara Metalworks",
      weather: "Sunny",
    },
    {
      date: "2025-05-24",
      timeOfDay: "Afternoon",
      activity: "Fishing",
      activityType: "Training",
      details: "Caught a Guardian fish",
      weather: "Sunny",
      statChanges: {
        Diligence: 1,
      },
    },
    {
      date: "2025-05-24",
      timeOfDay: "Evening",
      activity: "Watch Movie",
      activityType: "Social",
      details: "Trial of the Dragon at home",
      weather: "Sunny",
      statChanges: {
        Courage: 1,
      },
    },
    {
      date: "2025-05-25",
      timeOfDay: "Morning",
      activity: "Study",
      activityType: "Study",
      details: "Working on English vocabulary",
      weather: "Rainy",
      statChanges: {
        Knowledge: 1,
      },
    },
    {
      date: "2025-05-25",
      timeOfDay: "Afternoon",
      activity: "Social Link",
      activityType: "Social",
      details: "Spending time with Nanako at Junes",
      weather: "Rainy",
      statChanges: {
        Understanding: 1,
      },
    },
    {
      date: "2025-05-25",
      timeOfDay: "Evening",
      activity: "Rest",
      activityType: "Rest",
      details: "Recovering energy for the week ahead",
      weather: "Rainy",
    },
    {
      date: "2025-05-26",
      timeOfDay: "Evening",
      activity: "Basketball",
      activityType: "Training",
      details: "Practice with Kou and the team",
      weather: "Sunny",
      statChanges: {
        Diligence: 1,
        Understanding: 1,
      },
    },
    {
      date: "2025-05-27",
      timeOfDay: "Evening",
      activity: "Reading",
      activityType: "Reading",
      details: "Expert Study Methods",
      weather: "Cloudy",
      statChanges: {
        Knowledge: 1,
      },
    },
    {
      date: "2025-05-28",
      timeOfDay: "Evening",
      activity: "Hospital Visit",
      activityType: "Social",
      details: "Visiting the daycare nurse",
      weather: "Sunny",
      statChanges: {
        Expression: 1,
        Understanding: 1,
      },
    },
    {
      date: "2025-05-29",
      timeOfDay: "Evening",
      activity: "Band Practice",
      activityType: "Social",
      details: "Playing with Ayane in the music room",
      weather: "Sunny",
      statChanges: {
        Expression: 1,
      },
    },
    {
      date: "2025-05-30",
      timeOfDay: "Evening",
      activity: "Shrine Visit",
      activityType: "Social",
      details: "Making an offering at the shrine",
      weather: "Cloudy",
      statChanges: {
        Courage: 1,
      },
    },
    {
      date: "2025-05-31",
      timeOfDay: "Morning",
      activity: "Gardening",
      activityType: "Training",
      details: "Planting vegetables in the garden",
      weather: "Sunny",
      statChanges: {
        Diligence: 1,
      },
    },
    {
      date: "2025-05-31",
      timeOfDay: "Afternoon",
      activity: "Reading",
      activityType: "Reading",
      details: "Beginner's Fishing",
      weather: "Sunny",
      statChanges: {
        Knowledge: 1,
      },
    },
    {
      date: "2025-05-31",
      timeOfDay: "Evening",
      activity: "Cooking",
      activityType: "Training",
      details: "Making dinner with Nanako",
      weather: "Sunny",
      statChanges: {
        Diligence: 1,
        Understanding: 1,
      },
    },
    {
      date: "2025-06-01",
      timeOfDay: "Morning",
      activity: "TV Shopping",
      activityType: "Social",
      details: "Ordered a special item from Tanaka",
      weather: "Sunny",
    },
    {
      date: "2025-06-01",
      timeOfDay: "Afternoon",
      activity: "Reading",
      activityType: "Reading",
      details: "Atomic Habits by James Clear",
      weather: "Sunny",
      statChanges: {
        Knowledge: 1,
        Diligence: 1,
      },
    },
    {
      date: "2025-06-01",
      timeOfDay: "Evening",
      activity: "Homework",
      activityType: "Study",
      details: "Finishing math assignment",
      weather: "Sunny",
      statChanges: {
        Knowledge: 1,
      },
    },
  ],
  stats: {
    Knowledge: 2,
    Expression: 1,
    Diligence: 3,
    Understanding: 2,
    Courage: 1,
  },
}
